# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import visual_site_elements.models


class Migration(migrations.Migration):

    dependencies = [
        ('visual_site_elements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lg', 'Large'), ('md', 'Medium')], default='lg', max_length=20)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('width', models.CharField(blank=True, max_length=20, null=True)),
                ('media', models.ImageField(blank=True, height_field='height', null=True, upload_to=visual_site_elements.models.thumbnail_location, width_field='width')),
            ],
        ),
        migrations.DeleteModel(
            name='HorizontalBanner',
        ),
        migrations.RemoveField(
            model_name='promotionthumbnail',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='sliderimage',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='sliderimage',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='PromotionThumbnail',
        ),
        migrations.AddField(
            model_name='sliderthumbnail',
            name='slider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual_site_elements.SliderImage'),
        ),
    ]
