# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual_site_elements', '0002_auto_20170319_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
