# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual_site_elements', '0003_sliderimage_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'ordering': ['siralama']},
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='siralama',
            field=models.IntegerField(default=0),
        ),
    ]
