# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visual_site_elements', '0004_auto_20170323_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderimage',
            options={},
        ),
    ]
