# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visual_site_elements', '0005_auto_20170323_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImageTextFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=20, null=True)),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('siralama', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='tip',
            field=models.CharField(choices=[('Tip1', 'tip1'), ('Tip2', 'tip2')], default='tip1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sliderimagetextfields',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual_site_elements.SliderImage'),
        ),
    ]
