# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visual_site_elements', '0006_auto_20170420_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderimagetextfields',
            options={'ordering': ('siralama',)},
        ),
    ]
